### PR TITLE
 DigitalAccess@Home scheme to Phase out NEU PC Plus and Home Access programme

### PR DESCRIPTION
**Pull request by Tanbkadr**
From: Choong Mei chyi (SCHOOLS) 
Sent: Tuesday, May 23, 2023 1:48 PM
To: Tan Buck khoon adrian (SCHOOLS) 
Cc: Mohammad SHAIFUDIN (SCHOOLS); Keng Lian KWOK (SCHOOLS); Winefrede CHNG (SCHOOLS) ; Ling Ling TAN (SCHOOLS)
Subject: (SCH/032023/001) DigitalAccess@Home scheme and phasing out of NEU PC Plus and Home Access programme by 31 Mar 2023

Dear Adrian,

As per email below, please assist to remove NEU PC Plus information from our school’s website as the NEU PC Plus had ceased. 

Replace with the following :

DigitalAccess@Home
Applicants may apply for DigitalAccess@Home scheme online ([www.digitalaccess.gov.sg](http://www.digitalaccess.gov.sg/)).  They can also approach any of the 37 SG Digital community hubs and 4 self-help groups (CDAC, Eurasian Association, MENDAKI, SINDA) for assistance with applications. Applicants may use the online self-assessment tool (https://go.gov.sg/digitalaccesschecker) to check their eligibility before applying.

Thank you.

Regards
Maggie

### CODE REVIEW

**Comment by Tanbkadr** [comment]
added both approval personnel

**Comment by Tanbkadr** [comment]
updated

**Comment by Tanbkadr** [comment]
Updated as per Maggie request to remove the FAQs PDF file

**Review by putra1980 — APPROVED** [review]
Ok!

**Pull request merged**
